/**
 * Browser-side query helpers. Used by client components that fetch on mount
 * (sheets, the lightbox) and can't await a Server Component. Mirrors the
 * subset of the server queries we actually need from the client.
 *
 * Signed URLs are generated by the browser client here — the storage RLS
 * select policy scopes signing to the session user's own paths.
 */

import { createClient } from "@/lib/supabase/client";
import type { Trove, Gem, GemType, Tag } from "./types";
import {
  GEM_SELECT_WITH_TAGS,
  gemMediaUrl,
  mapGems,
  signedUrlMap,
  type GemRow,
} from "./util";

type TroveRow = {
  id: string;
  name: string;
  description: string | null;
  cover_gem_id: string | null;
  position: number;
  created_at: string;
};

type CoverableGem = {
  id: string;
  trove_id: string;
  type: GemType;
  storage_path: string | null;
  og_thumbnail_url: string | null;
};

export async function fetchGemById(id: string): Promise<Gem | null> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from("gems")
    .select(GEM_SELECT_WITH_TAGS)
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  if (!data) return null;
  const [gem] = await mapGems(supabase, [data as unknown as GemRow]);
  return gem ?? null;
}

export async function fetchTroveForEdit(id: string): Promise<{
  trove: Trove;
  gems: Pick<Gem, "id" | "type" | "media_url" | "storage_path">[];
} | null> {
  const supabase = createClient();
  const [troveRes, gemsRes] = await Promise.all([
    supabase
      .from("troves")
      .select("id, name, description, cover_gem_id, position, created_at")
      .eq("id", id)
      .maybeSingle(),
    supabase
      .from("gems")
      .select("id, trove_id, type, storage_path, og_thumbnail_url, created_at")
      .eq("trove_id", id)
      .order("created_at", { ascending: false }),
  ]);
  if (troveRes.error) throw troveRes.error;
  if (gemsRes.error) throw gemsRes.error;
  if (!troveRes.data) return null;
  const t = troveRes.data as TroveRow;
  const list = (gemsRes.data ?? []) as CoverableGem[];
  const signed = await signedUrlMap(
    supabase,
    list.map((g) => g.storage_path).filter((p): p is string => Boolean(p)),
  );
  const cover =
    (t.cover_gem_id && list.find((g) => g.id === t.cover_gem_id)) ||
    list[0] ||
    null;
  return {
    trove: {
      id: t.id,
      name: t.name,
      description: t.description,
      cover_gem_id: t.cover_gem_id,
      position: t.position,
      created_at: t.created_at,
      cover_url: cover ? gemMediaUrl(cover, signed) : null,
      gem_count: list.length,
    },
    gems: list.map((g) => ({
      id: g.id,
      type: g.type,
      storage_path: g.storage_path,
      media_url: gemMediaUrl(g, signed),
    })),
  };
}

export async function fetchAllTrovesLite(): Promise<
  Pick<Trove, "id" | "name">[]
> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from("troves")
    .select("id, name")
    .order("position")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return (data ?? []) as Pick<Trove, "id" | "name">[];
}

export async function fetchAllTagsLite(): Promise<Tag[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from("tags")
    .select("id, name")
    .order("name");
  if (error) throw error;
  return (data ?? []) as Tag[];
}
